config/routes.rb
Rails.application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Shoppe::Engine => "/shoppe"
  
  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  
  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'
  
  # 
  # Homepage
  #
  root :to => 'pages#home'
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter do
    if params[:category_id]
      @product_category = Shoppe::ProductCategory.where(:permalink => params[:category_id]).first!
    end
    if @product_category && params[:product_id]
      @product = @product_category.products.where(:permalink => params[:product_id]).active.first!      
    end
  end
  
  def index
    @products = @product_category.products.includes(:default_image, :product_categories, :variants).root.active
  end
  
  def filter
    @products = Shoppe::Product.active.with_attributes(params[:key].to_s, params[:value].to_s)
  end
  
  def categories
    @product_categories = Shoppe::ProductCategory.ordered.includes(:image)
  end
  
  def show
    @attributes = @product.product_attributes.public.to_a
  end
  
  def add_to_basket
    product_to_order = params[:variant] ? @product.variants.find(params[:variant].to_i) : @product
    current_order.order_items.add_item(product_to_order, params[:quantity].blank? ? 1 : params[:quantity].to_i)
    respond_to do |wants|
      wants.html { redirect_to request.referer }
      wants.json { render :json => {:added => true} }
    end
  rescue Shoppe::Errors::NotEnoughStock => e
    respond_to do |wants|
      wants.html { redirect_to request.referer, :alert => "We're sorry but we don't have enough stock to add that many products. We currently have #{e.available_stock} item(s) in stock. Please try again."}
      wants.json { render :json => {:error => 'NotEnoughStock', :available_stock => e.available_stock}}
    end
  end
  
end

app/views/products/categories.html.haml
- active_nav_item :catalogue
- @page_title = 'Catalogue'
.categories
  %table{:style => 'width:100%'}
    %tbody
      - @product_categories.each_slice(2) do |slice|
        %tr
          - slice.each do |category|
            %td.space
            %td
              %h4
                =link_to category.name, products_path(category.permalink)
              %p=category.short_description
            %td.space
            %td
              =link_to products_path(category.permalink) do
                =image_tag category.image ? category.image.path : '', { class: 'product-img' }
        %tr{:height => '20px;'}
      

app/views/products/filter.html.haml
- active_nav_item :catalogue
- @page_title = "#{params[:value]} - Products"
.category
  %h2 Products
  %p.intro Displaying products where <b>#{params[:key]}</b> is <b>#{params[:value]}</b>.
  - if @products.empty?
    %p.noProducts There are no products matching your filter
  - else
    = render 'shared/product_list', :products => @products

app/views/products/index.html.haml
- active_nav_item :catalogue
- @page_title = @product_category.name
.category
  %h2= @product_category.name
  - unless @product_category.description.blank?
    %h3.intro= @product_category.description
  - if @products.empty?
    %p.noProducts There are no products in this category
  - else
    = render 'shared/product_list', :products => @products

app/views/products/show.html.haml
- active_nav_item :catalogue
- @page_title = @product.name + " - " + @product.product_category.name
.product
  - path = @product.data_sheet.present? ? @product.data_sheet.path : image_path('default_disc.jpg')
  .img{:style => "background-image:url(#{path})"}
  %h2= @product.name
  %p.intro= @product.short_description
  
  - if @product.has_variants?
    %table.variants
      - for variant in @product.variants
        %tr
          %td
            -#- if variant.in_stock?
            -#  %p.stock.yes In stock
            -#- else
            -#  %p.stock.no Out of stock
            %h4= variant.name
            %p.price= number_to_currency variant.price
          -#%td.buy
          -#  = form_tag buy_product_path(@product.product_category.permalink, @product.permalink, :variant => variant.id), :class => (variant.in_stock? ? 'in-stock' : 'no-stock') do
          -#    %p
          -#      = select_tag 'quantity', options_for_select([1,2,3,4,5,6,7,8,9]), :disabled => !variant.in_stock?
          -#      = submit_tag 'Add to basket', :disabled => !variant.in_stock?
  - else
    .optionsBox
      .top
        %p.price= number_to_currency @product.price
        -#= form_tag buy_product_path(@product.product_category.permalink, @product.permalink), :class => (@product.in_stock? ? 'in-stock' : 'no-stock') do
        -#  %p
        -#    = select_tag 'quantity', options_for_select([1,2,3,4,5,6,7,8,9]), :disabled => !@product.in_stock?
        -#    = submit_tag 'Add to basket', :disabled => !@product.in_stock?
      -#.bottom
      -#  .stock
      -#    - if @product.in_stock?
      -#      %p.yes In stock
      -#      %p.time Order in the next <b>#{time_until_next_delivery_cut_off}</b> for delivery #{next_delivery_day}.
      -#    - else
      -#      %p.no Out of stock
      -#      %p.time Sorry - we don't have any stock of this product at the moment. #{link_to "Let me know when you do"}.
      -#  .links
      -#    %ul
      -#      - if @product.data_sheet
      -#        %li.item.datasheet= link_to "Read product datasheet", @product.data_sheet.path
      -#      - unless @product.in_the_box.blank?
      -#        %li.item.box
      -#          = link_to "What's in the box?"
      -#          %div.in_the_box
      -#            %h3 What's in the box?
      -#            = markdown @product.in_the_box
      -#      %li.item.ask= mail_to Shoppe.settings.email_address, "Ask us a question about this", :subject => "Question about the #{@product.name}"

    %hr

  - unless @attributes.empty?
    %table.attributes
      - for attribute in @attributes
        %tr
          %th= attribute.key
          %td= link_to attribute.value, product_filter_path(:key => attribute.key, :value => attribute.value)
  .description
    = markdown @product_category.description